services:
  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    volumes:
      - "customer-db-volume:/app/customer-service.db"

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    volumes:
      - "product-db-volume:/app/product.db"


  event-grid-viewer-site:
    build:
      context: ./event-grid-viewer
      dockerfile: Dockerfile
    ports:
      - "8003:8080"

volumes:
  product-db-volume:
  customer-db-volume: